# Generated by Django 3.2.8 on 2021-10-27 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images/realtors/')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('hire_date', models.DateField(blank=True, default=datetime.date(2021, 10, 27))),
                ('is_mvp', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='images/houses/')),
                ('photo_1', models.ImageField(blank=True, upload_to='images/houses/')),
                ('photo_2', models.ImageField(blank=True, upload_to='images/houses/')),
                ('photo_3', models.ImageField(blank=True, upload_to='images/houses/')),
                ('photo_4', models.ImageField(blank=True, upload_to='images/houses/')),
                ('photo_5', models.ImageField(blank=True, upload_to='images/houses/')),
                ('photo_6', models.ImageField(blank=True, upload_to='images/houses/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='btre.realtor')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateField(blank=True, default=datetime.date(2021, 10, 27))),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='btre.listing')),
            ],
        ),
    ]
